### POST request to save a new patient
POST http://localhost:4004/api/patients/add
Content-Type: application/json

{
  "name": "Osama Ahmed",
  "email": "osama@example.com",
  "address":"123 main street",
  "dateOfBirth": "1995-09-29",
  "registeredDate":"2025-06-12"
}
###