### PUT request to update existing patient
PUT http://localhost:4004/api/patients/361cd9f4-3ec3-4e95-91fc-677db31fc496
Content-Type: application/json

{
  "name": "Laura White",
  "email": "lura.white@example.com",
  "address":"789 Palm St, Springfield",
  "dateOfBirth": "1990-10-01"
}
###